import { Engine } from "@babylonjs/core/Engines/engine";
import { Scene } from "@babylonjs/core/scene";
import { FreeCamera } from "@babylonjs/core/Cameras/freeCamera";
import { Vector3 } from "@babylonjs/core/Maths/math.vector";
import { MeshBuilder } from "@babylonjs/core/Meshes/meshBuilder";
import { StandardMaterial } from "@babylonjs/core/Materials/standardMaterial";
import { DynamicTexture } from "@babylonjs/core/Materials/Textures/dynamicTexture";
import { Color3, Color4 } from "@babylonjs/core/Maths/math.color";

export type GameHandle={scene:Scene;dispose:()=>void};
type Action="left"|"right"|"jump"|"light"|"heavy"|"guard"|"dash"|"charge"|"transform";
type State="idle"|"walk"|"jump"|"attack"|"hit"|"guard"|"charge"|"transform"|"victory";
type Fighter={x:number;y:number;vx:number;vy:number;facing:1|-1;hp:number;ki:number;state:State;stateT:number;attackT:number;attackKind:"light"|"heavy";combo:number;comboWindow:number;hitFlash:number;aura:number;transformed:boolean;name:string;color:string;hair:string;ai:boolean;hitDone:boolean};
type Spark={x:number;y:number;vx:number;vy:number;life:number;color:string;size:number};
const W=960,H=540,GROUND=414;const held=new Set<Action>();const queue:Action[]=[];let bound=false;const sparks:Spark[]=[];
function bindKeys(){if(bound)return()=>{};bound=true;const map:Record<string,Action>={a:"left",d:"right",w:"jump",j:"light",k:"heavy",l:"guard",i:"charge",o:"transform",Shift:"dash"};const down=(e:KeyboardEvent)=>{const a=map[e.key];if(!a)return;e.preventDefault();if(!held.has(a))queue.push(a);held.add(a)};const up=(e:KeyboardEvent)=>{const a=map[e.key];if(a){held.delete(a);e.preventDefault()}};window.addEventListener("keydown",down);window.addEventListener("keyup",up);return()=>{window.removeEventListener("keydown",down);window.removeEventListener("keyup",up);held.clear();queue.length=0;bound=false}}
function take(a:Action){const i=queue.indexOf(a);if(i<0)return false;queue.splice(i,1);return true}
function makeFighter(x:number,name:string,color:string,hair:string,ai=false):Fighter{return{x,y:GROUND,vx:0,vy:0,facing:ai?-1:1,hp:100,ki:34,state:"idle",stateT:0,attackT:0,attackKind:"light",combo:0,comboWindow:0,hitFlash:0,aura:0,transformed:false,name,color,hair,ai,hitDone:false}}
function burst(x:number,y:number,color:string,n=12){for(let i=0;i<n;i++){const a=Math.random()*Math.PI*2,s=45+Math.random()*150;sparks.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.18+Math.random()*.35,color,size:2+Math.random()*5})}}
function startAttack(f:Fighter,kind:"light"|"heavy"){if(f.state==="attack"||f.state==="transform"||f.state==="hit")return;f.state="attack";f.stateT=0;f.attackT=kind==="heavy"?.48:.30;f.attackKind=kind;f.hitDone=false;f.combo=f.comboWindow>0?Math.min(3,f.combo+1):1;f.comboWindow=0}
function hurt(p:Fighter,att:Fighter){if(p.state==="guard"||p.hitFlash>0)return;const dmg=att.attackKind==="heavy"?14:8;p.hp=Math.max(0,p.hp-dmg);p.hitFlash=.13;p.state="hit";p.stateT=0;p.vx=att.facing*170;p.combo=0;burst(p.x,p.y-70,att.attackKind==="heavy"?"#ffb52e":"#fff4a6",att.attackKind==="heavy"?22:12)}
function update(f:Fighter,dt:number,enemy:Fighter){f.stateT+=dt;f.hitFlash=Math.max(0,f.hitFlash-dt);f.ki=Math.min(100,f.ki+dt*2);f.comboWindow=Math.max(0,f.comboWindow-dt);if(f.hp<=0){f.state="victory";f.vx=0;return}if(f.y<GROUND){f.vy+=700*dt;f.y+=f.vy*dt;if(f.y>=GROUND){f.y=GROUND;f.vy=0;if(f.state==="jump")f.state="idle"}}
 if(f.state==="transform"){f.vx=0;f.aura=Math.min(1,f.aura+dt*1.35);if(f.stateT>1.25){f.state="idle";f.transformed=true;f.hair="#ffd84d";f.ki=22;burst(f.x,f.y-72,"#ffe26b",42)}return}
 if(f.state==="attack"){f.vx=0;const total=f.attackKind==="heavy"?.48:.30,impact=f.attackKind==="heavy"?.17:.11;if(!f.hitDone&&f.stateT>=impact){f.hitDone=true;if(Math.abs(f.x-enemy.x)<135&&Math.abs(f.y-enemy.y)<105)hurt(enemy,f);else burst(f.x+f.facing*45,f.y-55,f.attackKind==="heavy"?"#ffb52e":"#fff4a6",6)}if(f.stateT>=total){f.state="idle";f.stateT=0;f.comboWindow=.42}return}
 if(f.state==="hit"){f.x+=f.vx*dt;f.vx*=Math.pow(.01,dt);if(f.stateT>.28)f.state="idle";f.x=Math.max(60,Math.min(900,f.x));return}
 if(f.ai){const d=enemy.x-f.x;f.facing=d>=0?1:-1;if(Math.abs(d)>170)f.vx=f.facing*72;else f.vx=0;if(Math.abs(d)<145&&f.stateT>1.1){startAttack(f,Math.random()<.72?"light":"heavy");f.stateT=0}}
 else {const dir=(held.has("right")?1:0)-(held.has("left")?1:0);if(take("transform")&&f.ki>=70&&!f.transformed){f.state="transform";f.stateT=0;return}if(take("light"))startAttack(f,"light");else if(take("heavy"))startAttack(f,"heavy");else if(held.has("jump")&&f.y===GROUND){f.vy=-355;f.state="jump"}else if(held.has("guard"))f.state="guard";else if(held.has("charge")){f.state="charge";f.aura=Math.min(1,f.aura+dt*.8)}else if(dir){f.vx=dir*(held.has("dash")?310:145);f.facing=dir as 1|-1;if(f.y===GROUND)f.state="walk"}else{f.vx=0;if(f.y===GROUND)f.state="idle"}}
 if(f.state==="charge"){if(!held.has("charge")){f.state="idle";f.aura=Math.max(0,f.aura-.15)}else{f.ki=Math.min(100,f.ki+dt*9);f.aura=Math.min(1,f.aura+dt*.55)}return}f.x+=f.vx*dt;f.x=Math.max(60,Math.min(900,f.x));f.vx*=Math.pow(.0005,dt)}
function backdrop(ctx:CanvasRenderingContext2D,t:number){const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,"#07142d");g.addColorStop(.55,"#155071");g.addColorStop(1,"#2b7470");ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.fillStyle="#b9e7d5";ctx.beginPath();ctx.arc(755,100,43,0,Math.PI*2);ctx.fill();ctx.fillStyle="#274a73";ctx.beginPath();ctx.moveTo(0,290);ctx.lineTo(110,225);ctx.lineTo(190,278);ctx.lineTo(300,208);ctx.lineTo(410,280);ctx.lineTo(530,215);ctx.lineTo(660,275);ctx.lineTo(800,200);ctx.lineTo(960,260);ctx.lineTo(960,415);ctx.lineTo(0,415);ctx.fill();ctx.fillStyle="#173552";ctx.beginPath();ctx.moveTo(0,340);ctx.lineTo(145,282);ctx.lineTo(260,337);ctx.lineTo(400,270);ctx.lineTo(535,338);ctx.lineTo(700,292);ctx.lineTo(830,345);ctx.lineTo(960,300);ctx.lineTo(960,415);ctx.lineTo(0,415);ctx.fill();ctx.fillStyle="#27324f";ctx.fillRect(0,GROUND+2,W,138);ctx.fillStyle="#3c4f70";ctx.fillRect(0,GROUND+2,W,12);for(let i=0;i<28;i++){ctx.fillStyle=i%2?"#56627e":"#c17b3e";ctx.fillRect((i*91+Math.floor(t*25))%960,GROUND+18+(i%3)*13,5+(i%4)*4,3)}}
function fighter(ctx:CanvasRenderingContext2D,f:Fighter,t:number){const bob=f.state==="idle"?Math.sin(t*7)*2:0;ctx.save();ctx.translate(f.x,f.y+bob);ctx.scale(f.facing,1);ctx.imageSmoothingEnabled=false;const aura=f.transformed||f.state==="transform"||f.state==="charge";if(aura){const pulse=1+Math.sin(t*18)*.1;ctx.globalAlpha=.16+.16*f.aura;ctx.fillStyle=f.transformed?"#ffd84d":"#58bfff";ctx.beginPath();ctx.ellipse(0,-68,48*pulse+f.aura*16,78*pulse+f.aura*18,0,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1}ctx.fillStyle="#151827";ctx.fillRect(-16,-88,32,27);ctx.fillStyle=f.hair;ctx.beginPath();ctx.moveTo(-18,-78);ctx.lineTo(-26,-112);ctx.lineTo(-7,-96);ctx.lineTo(0,-124);ctx.lineTo(8,-97);ctx.lineTo(28,-111);ctx.lineTo(18,-78);ctx.fill();ctx.fillStyle="#f0b98d";ctx.fillRect(-14,-76,28,25);ctx.fillStyle="#11152b";ctx.fillRect(5,-66,7,4);const atk=f.state==="attack",swing=atk?Math.sin(Math.min(1,f.stateT/(f.attackKind==="heavy"?.48:.30))*Math.PI):0;ctx.fillStyle=f.color;ctx.fillRect(-20,-48,40,40);ctx.fillStyle="#d63b4b";ctx.fillRect(-21,-18,42,7);ctx.fillStyle="#f0b98d";if(atk){ctx.save();ctx.translate(15,-40);ctx.rotate((f.attackKind==="heavy"?.8:.55)*swing);ctx.fillRect(0,-5,43,10);ctx.restore()}else ctx.fillRect(19,-43,11,28);ctx.fillRect(-30,-43,11,28);ctx.fillStyle="#20243c";if(f.state==="jump"){ctx.fillRect(-18,-10,14,18);ctx.fillRect(5,-4,14,12)}else{ctx.fillRect(-19,-12,16,27);ctx.fillRect(3,-12,16,27)}ctx.fillStyle="#0d1021";ctx.fillRect(-23,10,20,7);ctx.fillRect(3,10,22,7);if(atk){ctx.strokeStyle=f.attackKind==="heavy"?"#ffb52e":"#fff3a3";ctx.lineWidth=f.attackKind==="heavy"?8:5;ctx.beginPath();ctx.moveTo(30,-43);ctx.lineTo(65,-48);ctx.stroke()}if(f.state==="guard"){ctx.strokeStyle="#48c7ff";ctx.lineWidth=4;ctx.strokeRect(-38,-88,76,92)}if(f.state==="hit"){ctx.fillStyle="#ffec75";ctx.fillRect(30,-78,10,10)}ctx.restore()}
export async function createGameScene(engine:Engine,canvas:HTMLCanvasElement):Promise<GameHandle>{const scene=new Scene(engine);scene.clearColor=new Color4(.015,.02,.06,1);const camera=new FreeCamera("camera",new Vector3(0,0,-10),scene);camera.mode=FreeCamera.ORTHOGRAPHIC_CAMERA;camera.orthoLeft=-1;camera.orthoRight=1;camera.orthoTop=1;camera.orthoBottom=-1;const plane=MeshBuilder.CreatePlane("battle-canvas",{width:2,height:2},scene);const mat=new StandardMaterial("battle-mat",scene);mat.disableLighting=true;mat.emissiveColor=new Color3(1,1,1);const off=document.createElement("canvas");off.width=W;off.height=H;const ctx=off.getContext("2d")!;const tex=new DynamicTexture("battle-texture",off,scene,false);mat.diffuseTexture=tex;plane.material=mat;const p=makeFighter(315,"NOVA","#f28c28","#141526"),e=makeFighter(690,"RIVAL","#6d5dd3","#8c493d",true);let time=72,shake=0;const unbind=bindKeys();const before=scene.onBeforeRenderObservable.add(()=>{const dt=Math.min(.033,engine.getDeltaTime()/1000);time=Math.max(0,time-dt);update(p,dt,e);update(e,dt,p);if(p.state==="hit"||e.state==="hit")shake=Math.max(shake,5);shake=Math.max(0,shake-dt*20);for(let i=sparks.length-1;i>=0;i--){const s=sparks[i];s.life-=dt;s.x+=s.vx*dt;s.y+=s.vy*dt;s.vy+=180*dt;if(s.life<=0)sparks.splice(i,1)}ctx.clearRect(0,0,W,H);backdrop(ctx,time);const cam=Math.max(0,Math.min(220,(p.x+e.x)/2-480));ctx.save();ctx.translate(-cam+(Math.random()-.5)*shake,(Math.random()-.5)*shake);fighter(ctx,p,performance.now()/1000);fighter(ctx,e,performance.now()/1000);for(const s of sparks){ctx.globalAlpha=Math.max(0,s.life*3);ctx.fillStyle=s.color;ctx.fillRect(s.x,s.y,s.size,s.size)}ctx.restore();tex.update();window.dispatchEvent(new CustomEvent("cpf-state",{detail:{pHp:p.hp,pKi:p.ki,eHp:e.hp,eKi:e.ki,time,combo:p.combo,state:p.state,enemyState:e.state,transform:p.transformed}}))});return{scene,dispose:()=>{scene.onBeforeRenderObservable.remove(before);unbind();scene.dispose()}}}
