// Style reminder: 胶囊星球像素剧场；所有战斗反馈遵循清晰轮廓、暖橙角色、电蓝能量、Capsule Amber 命中火花与街机节奏。
import { Engine } from "@babylonjs/core/Engines/engine";
import { Scene } from "@babylonjs/core/scene";
import { FreeCamera } from "@babylonjs/core/Cameras/freeCamera";
import { Vector3 } from "@babylonjs/core/Maths/math.vector";
import { MeshBuilder } from "@babylonjs/core/Meshes/meshBuilder";
import { StandardMaterial } from "@babylonjs/core/Materials/standardMaterial";
import { DynamicTexture } from "@babylonjs/core/Materials/Textures/dynamicTexture";
import { Texture } from "@babylonjs/core/Materials/Textures/texture";
import { Color3, Color4 } from "@babylonjs/core/Maths/math.color";

export type GameHandle = { scene: Scene; dispose: () => void };
type Action = "left" | "right" | "jump" | "light" | "heavy" | "guard" | "dash" | "charge" | "transform";
type FighterState = "idle" | "walk" | "jump" | "attack" | "hit" | "guard" | "charge" | "transform" | "victory";
type Fighter = { x:number; y:number; vx:number; vy:number; facing:1|-1; hp:number; ki:number; state:FighterState; stateT:number; attackT:number; combo:number; aura:number; flash:number; name:string; color:string; hair:string; ai:boolean };
type Spark = { x:number; y:number; vx:number; vy:number; life:number; color:string; size:number };

const W = 960, H = 540, GROUND = 414;
const bgUrl = "/manus-storage/capsule-planet-battlefield_23b7c8e5.png";
const actions = new Set<Action>();
const sparks: Spark[] = [];
let keyBound = false;

function makeFighter(x:number, name:string, color:string, hair:string, ai=false): Fighter { return { x, y:GROUND, vx:0, vy:0, facing: ai ? -1 : 1, hp:100, ki:34, state:"idle", stateT:0, attackT:0, combo:0, aura:0, flash:0, name, color, hair, ai }; }
function bindKeys() { if (keyBound) return () => {}; keyBound=true; const map:Record<string,Action>={a:"left",d:"right",w:"jump",j:"light",k:"heavy",l:"guard",i:"charge",o:"transform",Shift:"dash"}; const down=(e:KeyboardEvent)=>{const a=map[e.key]; if(a){actions.add(a); e.preventDefault();}}; const up=(e:KeyboardEvent)=>{const a=map[e.key]; if(a) actions.delete(a);}; window.addEventListener("keydown",down); window.addEventListener("keyup",up); return ()=>{window.removeEventListener("keydown",down);window.removeEventListener("keyup",up); keyBound=false;}; }
function burst(x:number,y:number,color:string,count=10){ for(let i=0;i<count;i++){const a=Math.random()*Math.PI*2,s=30+Math.random()*100;sparks.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.25+Math.random()*.35,color,size:2+Math.random()*4});} }
function updateFighter(f:Fighter, dt:number, p:Fighter){
  f.stateT+=dt; f.flash=Math.max(0,f.flash-dt); f.ki=Math.min(100,f.ki+dt*2);
  if(f.y<GROUND){ f.vy+=680*dt; f.y+=f.vy*dt; if(f.y>=GROUND){f.y=GROUND;f.vy=0;if(f.state==="jump")f.state="idle";} }
  if(f.hp<=0){ f.state="victory"; f.vx=0; return; }
  if(f.ai){ const dist=p.x-f.x; f.facing=dist>=0?1:-1; if(Math.abs(dist)>210) f.vx=f.facing*75; else f.vx=0; if(Math.abs(dist)<145 && f.stateT>1.2){f.state="attack";f.stateT=0;f.attackT=.34;} }
  else { const dir=(actions.has("right")?1:0)-(actions.has("left")?1:0); f.vx=dir* (actions.has("dash")?330:150); if(dir)f.facing=dir as 1|-1; if(actions.has("jump")&&f.y===GROUND){f.vy=-350;f.state="jump";} if(actions.has("guard")){f.state="guard";} else if(actions.has("charge")){f.state="charge";f.aura=Math.min(1,f.aura+dt*.55);} else if(actions.has("transform")&&f.ki>72){f.state="transform";f.stateT=0;f.aura=1;} else if(actions.has("heavy")||actions.has("light")){if(f.state!=="attack"){f.state="attack";f.stateT=0;f.attackT=actions.has("heavy")?.52:.32;}} else if(dir&&f.y===GROUND)f.state="walk"; else if(f.y===GROUND&&f.state!=="transform")f.state="idle"; }
  if(f.state==="transform"){f.vx=0;f.aura=Math.min(1,f.aura+dt*1.8);if(f.stateT>.92){f.state="idle";f.ki=18;f.hair="#ffd84d";}}
  if(f.state==="attack"){f.attackT-=dt;if(f.attackT<=0){if(Math.abs(f.x-p.x)<125&&Math.abs(f.y-p.y)<95&&p.state!=="guard"&&p.flash<=0){const dmg=f.ai?7: (actions.has("heavy")?15:9);p.hp=Math.max(0,p.hp-dmg);p.flash=.14;p.state="hit";p.stateT=0;p.vx=f.facing*190;p.combo=f.combo+1;f.combo++;burst(p.x,p.y-74,actions.has("heavy")?"#f6a62c":"#fff3a3",actions.has("heavy")?18:10);} f.state="idle";f.stateT=0;f.combo=0;}}
  if(f.state==="hit"&&f.stateT>.25)f.state="idle"; f.x+=f.vx*dt; f.x=Math.max(70,Math.min(890,f.x)); f.vx*=Math.pow(.0005,dt);
}
function drawBackdrop(ctx:CanvasRenderingContext2D, t:number){ const sky=ctx.createLinearGradient(0,0,0,H); sky.addColorStop(0,"#071229"); sky.addColorStop(.52,"#16466b"); sky.addColorStop(1,"#2b6e72"); ctx.fillStyle=sky;ctx.fillRect(0,0,W,H); ctx.fillStyle="#b4e6d3";ctx.beginPath();ctx.arc(752,102,42,0,Math.PI*2);ctx.fill(); ctx.fillStyle="#274a73";ctx.beginPath();ctx.moveTo(0,290);ctx.lineTo(100,232);ctx.lineTo(182,278);ctx.lineTo(290,208);ctx.lineTo(385,278);ctx.lineTo(520,218);ctx.lineTo(640,275);ctx.lineTo(790,200);ctx.lineTo(960,264);ctx.lineTo(960,415);ctx.lineTo(0,415);ctx.fill(); ctx.fillStyle="#173552";ctx.beginPath();ctx.moveTo(0,340);ctx.lineTo(135,285);ctx.lineTo(252,338);ctx.lineTo(390,270);ctx.lineTo(520,340);ctx.lineTo(690,292);ctx.lineTo(820,348);ctx.lineTo(960,300);ctx.lineTo(960,415);ctx.lineTo(0,415);ctx.fill(); for(let i=0;i<6;i++){const x=90+i*170;ctx.fillStyle="#3e9a91";ctx.fillRect(x,300-(i%2)*15,16,92);ctx.fillRect(x-22,322-(i%2)*15,60,8);ctx.fillRect(x-14,307-(i%2)*15,44,7);} ctx.fillStyle="#7fced0";ctx.fillRect(705,320,82,42);ctx.fillStyle="#efb35a";ctx.fillRect(719,298,52,22);ctx.fillStyle="#20284b";ctx.fillRect(731,332,14,30);ctx.fillRect(756,332,14,30);ctx.fillStyle="rgba(124,225,220,.24)";ctx.fillRect(705,314,82,6); ctx.fillStyle="#27324f";ctx.fillRect(0,GROUND+8,W,126); ctx.fillStyle="#3c4f70";ctx.fillRect(0,GROUND+2,W,12); for(let i=0;i<25;i++){ctx.fillStyle=i%2?"#56627e":"#c17b3e";ctx.fillRect((i*97+Math.floor(t*18))%960,GROUND+18+(i%3)*12,5+(i%4)*4,3);} }
function drawFighter(ctx:CanvasRenderingContext2D,f:Fighter){ const x=f.x,y=f.y; ctx.save(); ctx.translate(x,y); ctx.scale(f.facing,1); ctx.imageSmoothingEnabled=false; const bob=f.state==="idle"?Math.sin(performance.now()/180)*2:0; ctx.translate(0,bob); if(f.aura>.08||f.state==="transform"){ctx.globalAlpha=.22+.22*f.aura;ctx.fillStyle="#ffd84d";ctx.beginPath();ctx.ellipse(0,-70,42+f.aura*20,76+f.aura*20,0,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;}
  ctx.fillStyle="#1a1b2e";ctx.fillRect(-15,-88,30,28); ctx.fillStyle=f.hair; ctx.beginPath();ctx.moveTo(-18,-78);ctx.lineTo(-24,-112);ctx.lineTo(-7,-96);ctx.lineTo(0,-122);ctx.lineTo(8,-97);ctx.lineTo(28,-110);ctx.lineTo(17,-78);ctx.fill(); ctx.fillStyle="#f0b98d";ctx.fillRect(-14,-76,28,25); ctx.fillStyle="#10152d";ctx.fillRect(f.facing>0?4:-11,-66,7,4); ctx.fillStyle=f.color;ctx.fillRect(-20,-48,40,42);ctx.fillStyle="#f0b98d";ctx.fillRect(-30,-43,11,29);ctx.fillRect(19,-43,11,29);ctx.fillStyle="#d63b4b";ctx.fillRect(-21,-19,42,7);ctx.fillStyle="#20243c";ctx.fillRect(-19,-12,16,27);ctx.fillRect(3,-12,16,27);ctx.fillStyle="#0d1021";ctx.fillRect(-23,10,20,7);ctx.fillRect(3,10,22,7);
  if(f.state==="attack"){ctx.strokeStyle="#fff3a3";ctx.lineWidth=6;ctx.beginPath();ctx.moveTo(14,-34);ctx.lineTo(58,-40);ctx.stroke();} if(f.state==="guard"){ctx.strokeStyle="#48c7ff";ctx.lineWidth=3;ctx.strokeRect(-34,-83,68,88);} if(f.state==="hit"){ctx.fillStyle="#ffec75";ctx.fillRect(28,-76,9,9);} ctx.restore(); }

export async function createGameScene(engine:Engine, canvas:HTMLCanvasElement):Promise<GameHandle>{
  const scene=new Scene(engine); scene.clearColor=new Color4(0.015,0.02,0.06,1); const camera=new FreeCamera("camera",new Vector3(0,0,-10),scene); camera.mode=FreeCamera.ORTHOGRAPHIC_CAMERA; camera.orthoLeft=-1; camera.orthoRight=1; camera.orthoTop=1; camera.orthoBottom=-1;
  const bgPlane=MeshBuilder.CreatePlane("background-stage",{width:2,height:2},scene); const bgMat=new StandardMaterial("background-mat",scene); bgMat.disableLighting=true; bgMat.emissiveColor=new Color3(1,1,1); const bgTexture=new Texture(bgUrl,scene); bgMat.diffuseTexture=bgTexture; bgPlane.material=bgMat; const plane=MeshBuilder.CreatePlane("pixel-stage",{width:2,height:2},scene); const mat=new StandardMaterial("pixel-mat",scene); mat.disableLighting=true; mat.emissiveColor=new Color3(1,1,1); const off=document.createElement("canvas");off.width=W;off.height=H; const ctx=off.getContext("2d")!; const tex=new DynamicTexture("stage-texture",off,scene,false); tex.hasAlpha=true;mat.diffuseTexture=tex;mat.useAlphaFromDiffuseTexture=true;plane.material=mat; plane.position.z=-0.01;
  const bg=new Image(); bg.crossOrigin="anonymous"; bg.src=bgUrl; let bgReady=false; bg.onload=()=>bgReady=true; bg.onerror=()=>{bgReady=false;};
  const p=makeFighter(310,"NOVA","#f28c28","#141526"); const e=makeFighter(690,"RIVAL","#6d5dd3","#8c493d",true); let time=72, hitstop=0, shake=0; const unbind=bindKeys(); const demo=new URLSearchParams(location.search).has("demo"); const emit=()=>window.dispatchEvent(new CustomEvent("cpf-state",{detail:{pHp:p.hp,pKi:p.ki,eHp:e.hp,eKi:e.ki,time,combo:p.combo,state:p.state,enemyState:e.state,transform:p.hair==="#ffd84d"}}));
  const before=scene.onBeforeRenderObservable.add(()=>{const dt=Math.min(.033,engine.getDeltaTime()/1000); if(hitstop>0){hitstop-=dt;return;} time=Math.max(0,time-dt); if(demo&&Math.floor(time*2)%7===0){actions.add("right");if(Math.abs(p.x-e.x)<150)actions.add("light");} updateFighter(p,dt,e); updateFighter(e,dt,p); if(p.state==="hit"||e.state==="hit"){hitstop=.075;shake=5;} shake=Math.max(0,shake-dt*22); for(let i=sparks.length-1;i>=0;i--){const s=sparks[i];s.life-=dt;s.x+=s.vx*dt;s.y+=s.vy*dt;s.vy+=100*dt;if(s.life<=0)sparks.splice(i,1);}
    ctx.clearRect(0,0,W,H); if(!bgReady)drawBackdrop(ctx,time); else {ctx.fillStyle="rgba(8,10,28,.10)";ctx.fillRect(0,0,W,H); } const cam=(p.x+e.x)/2-480; ctx.save();ctx.translate(-cam+(Math.random()-.5)*shake,Math.random()*shake); if(bgReady){ctx.fillStyle="#161b34";ctx.fillRect(0,GROUND+8,960,118);ctx.fillStyle="#2a3451";ctx.fillRect(0,GROUND+2,960,12); for(let i=0;i<25;i++){ctx.fillStyle=i%2?"#56627e":"#c17b3e";ctx.fillRect((i*97+Math.floor(time*18))%960,GROUND+18+(i%3)*12,5+(i%4)*4,3);}} drawFighter(ctx,p);drawFighter(ctx,e); for(const s of sparks){ctx.globalAlpha=Math.max(0,s.life*3);ctx.fillStyle=s.color;ctx.fillRect(s.x,s.y,s.size,s.size);ctx.globalAlpha=1;} ctx.restore(); tex.update(); emit();
  });
  return {scene,dispose:()=>{scene.onBeforeRenderObservable.remove(before);unbind();scene.dispose();}};
}
